import type { RoleDefinition, RoleId } from "./types";

export const roleDefinitions: Record<RoleId, RoleDefinition> = {
  killer: {
    id: "killer",
    displayName: "Killer",
    team: "killer",
    icon: "knife",
    description: "Avoid being caught. Choose one victim each night.",
    nightAction: "kill",
    selfTarget: false,
    order: 10,
    privateResult: "none",
    publicResult: "victim_only",
    actsWhileDead: false,
    countsForWin: true,
  },
  doctor: {
    id: "doctor",
    displayName: "Doctor",
    team: "village",
    icon: "heart-pulse",
    description: "Protect one living player each night.",
    nightAction: "protect",
    selfTarget: true,
    order: 20,
    privateResult: "none",
    publicResult: "none",
    actsWhileDead: false,
    countsForWin: false,
  },
  sheriff: {
    id: "sheriff",
    displayName: "Sheriff",
    team: "village",
    icon: "badge",
    description: "Investigate one player. You receive only YES or NO.",
    nightAction: "investigate",
    selfTarget: false,
    order: 30,
    privateResult: "sheriff_yes_no",
    publicResult: "none",
    actsWhileDead: false,
    countsForWin: false,
  },
  villager: {
    id: "villager",
    displayName: "Villager",
    team: "village",
    icon: "users",
    description: "No night power. Listen closely and vote wisely.",
    selfTarget: false,
    order: 99,
    privateResult: "none",
    publicResult: "none",
    actsWhileDead: false,
    countsForWin: false,
  },
};

export const roleIntroLines: Record<RoleId, string[]> = {
  killer: ["Smile normally.", "Trust nobody.", "Choose carefully."],
  doctor: ["Apparently you are qualified.", "Try to keep someone alive.", "No pressure."],
  sheriff: ["Everyone looks suspicious.", "Ask the right question.", "You only get YES or NO."],
  villager: ["No special powers.", "Just logic, lies, and questionable friends.", "Listen harder."],
};
